After first run no longer need to specify the ups.

diff --git a/chipmonk b/chipmonk
--- a/chipmonk
+++ b/chipmonk
@@ -2,9 +2,8 @@
 
 # # # Chipmonk
 # # # Author: Marshall Whittaker / oxagast
-# # # Version: 1.1
+# # # Version: 1.3
 # # # NUT (Network UPS Tools) Visual Power Dialog
-
 
 function playball()
 {
@@ -13,9 +12,6 @@ function playball()
   echo "Logging UPS power details to /var/log/ups.log"
   syslog_popup
   echo "Monitoring syslog for UPS state changes"
-  echo
-  echo "Now add this script as a startup script for your user!"
-  echo
 }
 
 function clean_up()
@@ -26,12 +22,11 @@ function clean_up()
 
 function set_perms()
 {
-read -p "Would you like to give /usr/bin/upslog sgid nut? Warning! This is a potential security risk. " -n 1 -r
-echo    # (optional) move to a new line
-if [[ ! $REPLY =~ ^[Yy]$ ]]
-then
+  read -p "Would you like to give /usr/bin/upslog sgid nut? Warning! This is a potential security risk. " -n 1 -r
+  echo # (optional) move to a new line
+  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
     exit 1
-fi
+  fi
   if [ $(whoami) == "root" ]; then
     echo "Fixing permissions for first run..."
     echo "Setting group permissions on /usr/bin/upslog"
@@ -48,7 +43,7 @@ function startup()
 {
   echo "Starting dialogs for $model"
   echo "Checking upslog permissions"
-  ls -al /usr/bin/upslog /var/log/ups.log
+  # ls -al /usr/bin/upslog /var/log/ups.log
   touch /var/log/ups.log
   chmod g+rw /var/log/ups.log
   chown root:nut /var/log/ups.log
@@ -56,37 +51,33 @@ function startup()
     if [[ $(stat -L -c "%A" /var/log/ups.log | cut -c 6) == "w" ]]; then
       if [[ $(stat -c "%G" /usr/bin/upslog) == "nut" ]]; then
         if [[ $(stat -c "%G" /var/log/ups.log) == "nut" ]]; then
-
           playball
         fi
 
       fi
     fi
-  echo "Sorry, UPS logging facility couldn't be set up properly..."
-  syslog_popup;
+    echo "Sorry, UPS logging facility couldn't be set up properly..."
+    syslog_popup
   else
-
     set_perms
   fi
 }
 
 function log_ups()
 {
-  echo "Checking /var/log/ups.log permissions!"
   if [ $(stat -c "%A" /var/log/ups.log | cut -c -6) == "w" ]; then
-  if [ $(stat -c "%G" /var/log/ups.log) == "nut" ]; then
-
-  echo "Starting detailed logger: /var/log/ups.log"
-  upslog -l /var/log/ups.log -s $model -f "%host% %upshost% %time @Y-@M-@d @H:@M% STA:%VAR ups.status% CRG:%VAR battery.charge% INP:%VAR input.voltage% LOD:%VAR ups.load% TMP:%VAR ups.temperature%" || echo "Logging couldn't be established?"
+    if [ $(stat -c "%G" /var/log/ups.log) == "nut" ]; then
+      echo "Starting detailed logger: /var/log/ups.log"
+      upslog -l /var/log/ups.log -s $model -f "%host% %upshost% %time @Y-@M-@d @H:@M% STA:%VAR ups.status% CRG:%VAR battery.charge% INP:%VAR input.voltage% LOD:%VAR ups.load% TMP:%VAR ups.temperature%" || echo "Logging couldn't be established?"
+    fi
   fi
-fi
 }
 
 function syslog_popup()
 {
   f="/var/log/syslog"
   curr=$(<"$f")
-  inotifywait -m -e modify "$f" --format "%e" | while read -r event; do
+  inotifywait -m -e modify "$f" --format "%e" | while read -r event 2>/dev/null; do
     if [ "$event" == "MODIFY" ]; then
       prev="$curr"
       curr=$(cat "$f" | tail -n 1)
@@ -101,20 +92,29 @@ function syslog_popup()
   done
 }
 
-if [[ "$#" -ne 1 ]]; then
+echo "# # # Chipmonk # # #"
+echo "NUT (Network UPS Tools) Visual Power Dialogs"
+echo "Author: Marshall Whittaker / oxagast"
+logperm=2
+if [[ "$#" -gt 1 ]]; then
   echo "You need to specify the NUT configured UPS model@hostname: "
   echo "    ./chipmonk.sh SK600@jerkon"
   exit
-else
-  echo "# # # Chipmonk # # #"
-  echo "NUT (Network UPS Tools) Visual Power Dialogs"
-  echo "Author: Marshall Whittaker / oxagast"
-  echo
-  model=$1
-  logperm=2
-  if [ $(echo $model | grep  ".@."| wc -l) -gt 0 ]; then
-    startup
-  else echo "Incorrect model@hostname syntax"
-  fi
 fi
-
+if [[ "$#" -eq 0 ]]; then
+  model=$(grep "[MODEL]" -A 1 ~/.chipmonk | tail -n 1 | tr -d '\n')
+  if [ $(echo $model | grep ".@." | wc -l) -eq 1 ]; then
+    startup
+  fi
+else
+  if [[ "$#" -eq 1 ]]; then
+    model=$1
+    if [ $(echo $model | grep ".@." | wc -l) -eq 1 ]; then
+      echo "[MODEL]" >~/.chipmonk
+      echo $model >>~/.chipmonk
+      startup
+    fi
+  fi
+  echo "You need to specify the NUT configured UPS model@hostname: "
+  echo "    ./chipmonk.sh SK600@jerkon"
+fi
